# -*- coding: utf-8 -*-
"""ibge_ingestao_sqlite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxQhO_MucaGEHWVCSzutGRAPNz7vYHLs
"""

# 🔁 Etapa 1: importar bibliotecas
import requests
import pandas as pd
from datetime import date

# 🔁 Etapa 2: definir função para coletar estados
def coletar_estados_ibge():
    url = "https://servicodados.ibge.gov.br/api/v1/localidades/estados"
    resposta = requests.get(url)
    dados = resposta.json()
    df = pd.DataFrame(dados)
    return df[['id', 'sigla', 'nome']]

# 🔁 Etapa 3: coletar e salvar CSV
df = coletar_estados_ibge()
arquivo = f"ibge_estados_{date.today().isoformat()}.csv"
df.to_csv(arquivo, index=False)

print("Arquivo gerado com sucesso:", arquivo)

import sqlite3
import os

from google.colab import drive
drive.mount('/content/drive')

# Caminho para salvar o banco no seu Google Drive
caminho_banco = "/content/drive/MyDrive/datalake/ibge.db"

# Conecta ou cria o banco
conn = sqlite3.connect(caminho_banco)

# Grava a tabela 'estados' (substitui se já existir)
df.to_sql("estados", conn, if_exists="replace", index=False)

conn.close()
print("Tabela 'estados' salva com sucesso no banco SQLite.")

# Reabre conexão
conn = sqlite3.connect(caminho_banco)

# Consulta dados da tabela
df_verificacao = pd.read_sql("SELECT * FROM estados", conn)
conn.close()

df_verificacao.head()

def consultar_sql(query, caminho_banco=caminho_banco):
    import sqlite3
    import pandas as pd

    # Abre conexão com o banco
    conn = sqlite3.connect(caminho_banco)

    # Executa a consulta e retorna DataFrame
    df_resultado = pd.read_sql(query, conn)

    # Fecha conexão
    conn.close()

    return df_resultado

# Exemplo: buscar todos os estados
sql = "SELECT * FROM estados"
df = consultar_sql(sql)
print(df)

# Exemplo: filtrar estados que começam com "A"
sql = "SELECT * FROM estados WHERE nome LIKE 'A%'"
df = consultar_sql(sql)
print(df.head())