name: Carga diária IBGE

on:
  schedule:
    - cron: '0 12 * * *'  # Executa todo dia às 9h (horário de Brasília)
  workflow_dispatch:      # Permite execução manual no GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Executar script de ingestão
      run: python ingestao_ibge.py
